### ISSUE TITLE
报了一个错bug，麻烦给指导下

### ISSUE THREAD

**Issue by laipistilton** [srcrs/UnicomTask#13]
ERROR:【游戏中心签到】: 错误，原因为: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 123, in gameCenterSign_Task
    res = gameCenter.json()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

是不是接口数据发生改变了？

**Comment by srcrs** [comment]
@laipistilton 数据接口变得应该不会那么快，估计是偶然网络请求错误了，你再重新运行试一次。

**Comment by laipistilton** [comment]
好的，谢谢&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "srcrs"<notifications@github.com&gt;; 
发送时间: 2021年2月20日(星期六) 下午2:48
收件人: "srcrs/UnicomTask"<UnicomTask@noreply.github.com&gt;; 
抄送: "生活在别处"<54862713@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [srcrs/UnicomTask] 报了一个错bug，麻烦给指导下 (#13)





 
@laipistilton 数据接口变得应该不会那么快，估计是偶然网络请求错误了，你再重新运行试一次。
