### ISSUE TITLE
Github Action运行失败

### ISSUE THREAD

**Issue by askiter** [srcrs/UnicomTask#235]
前几天配置好的，USERS_COVER也配置好了，当时手工跑了一下，是正常的，但是之后的自动化运行都不行
#***group***Run echo "$USERS_COVER" > ./config.json
***36;1mecho "$USERS_COVER" > ./config.json***0m
***36;1mpython main.py***0m
shell: /bin/bash -e ***0***
env:
  pythonLocation: /opt/hostedtoolcache/Python/3.9.2/x64
  LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.2/x64/lib
  USERS_COVER: ***
##***endgroup***
***2021-03-14 09:11:11,115***:ERROR:账号信息获取失败错误，原因为: Expecting property name enclosed in double quotes: line 10 column 5 (char 436)
***2021-03-14 09:11:11,116***:ERROR:1.请检查是否在Secrets添加了账号信息，以及添加的位置是否正确。
***2021-03-14 09:11:11,116***:ERROR:2.填写之前，是否在网站验证过Json格式的正确性。
Traceback (most recent call last):
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 555, in <module>
    main("","")
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 516, in main
Traceback (most recent call last):
  File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 343, in readJson
    users = json.load(fp)
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 10 column 5 (char 436)

    for user in users:
TypeError: 'NoneType' object is not iterable
##***error***Process completed with exit code 1.

请问这个问题如何解决，谢谢

**Comment by askiter** [comment]
看错误日志里面开头几行 ./config.json 后面都有些乱码

groupRun echo "$USERS_COVER" > ./config.json
�36;1mecho "$USERS_COVER" > ./config.json�0m
�36;1mpython main.py�0m

是不是这个问题导致的呢
