### ISSUE TITLE
Github Action部署腾讯云Serverless上传文件400错误

### ISSUE THREAD

**Issue by 1eif** [srcrs/UnicomTask#242]
错误发生在Uploading...
具体报错信息如下
`+ serverless@2.29.0
added 605 packages from 422 contributors in 22.744s
开始部署至腾讯云函数
***?25l***JInitializing...
***G***JAction: "deploy" - Stage: "dev" - App: "unicom" - Instance: "main"
***G***JUploading...
***G***G***J***J
***J Error: Request failed with status code 400
    at createError (/usr/local/lib/node_modules/serverless/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/serverless/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/serverless/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
***G
572s › main › Request failed with status code 400  `

**Comment by srcrs** [comment]
> 错误发生在Uploading...
> 具体报错信息如下
> 
> ```
> + serverless@2.29.0
> added 605 packages from 422 contributors in 22.744s
> 开始部署至腾讯云函数
> �***?25l�***JInitializing...
> �***G�***JAction: "deploy" - Stage: "dev" - App: "unicom" - Instance: "main"
> �***G�***JUploading...
> �***G�***G�***J�***J
> �***J Error: Request failed with status code 400
>     at createError (/usr/local/lib/node_modules/serverless/node_modules/axios/lib/core/createError.js:16:15)
>     at settle (/usr/local/lib/node_modules/serverless/node_modules/axios/lib/core/settle.js:17:12)
>     at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/serverless/node_modules/axios/lib/adapters/http.js:260:11)
>     at IncomingMessage.emit (events.js:327:22)
>     at endReadableNT (internal/streams/readable.js:1327:12)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)
> �***G
> 572s › main › Request failed with status code 400
> ```

最近网络不太好。把代码拷贝到本地，账号信息填到config.json，然后在`./UnicomTask`目录下执行 `bash local_deploy.sh`也可以。

**Comment by 1eif** [comment]
> > 错误发生在Uploading...
> > 具体报错信息如下
> > ```
> > + serverless@2.29.0
> > added 605 packages from 422 contributors in 22.744s
> > 开始部署至腾讯云函数
> > �***?25l�***JInitializing...
> > �***G�***JAction: "deploy" - Stage: "dev" - App: "unicom" - Instance: "main"
> > �***G�***JUploading...
> > �***G�***G�***J�***J
> > �***J Error: Request failed with status code 400
> >     at createError (/usr/local/lib/node_modules/serverless/node_modules/axios/lib/core/createError.js:16:15)
> >     at settle (/usr/local/lib/node_modules/serverless/node_modules/axios/lib/core/settle.js:17:12)
> >     at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/serverless/node_modules/axios/lib/adapters/http.js:260:11)
> >     at IncomingMessage.emit (events.js:327:22)
> >     at endReadableNT (internal/streams/readable.js:1327:12)
> >     at processTicksAndRejections (internal/process/task_queues.js:80:21)
> > �***G
> > 572s › main › Request failed with status code 400
> > ```
> 
> 最近网络不太好。把代码拷贝到本地，账号信息填到config.json，然后在`./UnicomTask`目录下执行 `bash local_deploy.sh`也可以。

Roger that
