### ISSUE TITLE
防刷策略接口校验不通过

### ISSUE THREAD

**Issue by hillockgang** [srcrs/UnicomTask#27]
【每日签到】: 错误，原因为: **Expecting value: line 1 column 1 (char 0)** 
【天天抽奖】: 谢谢参与~ x1 【天天抽奖】: 谢谢参与~ x2 【天天抽奖】: 2MB x3 【积分抽奖】: 谢谢参与~ x免费 
【游戏中心签到】: 打卡成功，奖励发放失败 【游戏频道打卡】: **积分领取接口:防刷策略接口校验不通过** 

 我**不清楚**具体原因。

1. 请求添加一个GitHub Environments 用来设置延时时长，**个性化**调整脚本**执行时间**的功能

**Comment by srcrs** [comment]
> 【每日签到】: 错误，原因为: **Expecting value: line 1 column 1 (char 0)** 
> 【天天抽奖】: 谢谢参与~ x1 【天天抽奖】: 谢谢参与~ x2 【天天抽奖】: 2MB x3 【积分抽奖】: 谢谢参与~ x免费 
> 【游戏中心签到】: 打卡成功，奖励发放失败 【游戏频道打卡】: **积分领取接口:防刷策略接口校验不通过** 
> 
>  我**不清楚**具体原因。
> 
> 1. 请求添加一个GitHub Environments 用来设置延时时长，**个性化**调整脚本**执行时间**的功能

可以，我一会看下触发接口校验是什么原因，貌似调整执行时间也不能解决。

**Comment by srcrs** [comment]
> > 【每日签到】: 错误，原因为: **Expecting value: line 1 column 1 (char 0)**
> > 【天天抽奖】: 谢谢参与~ x1 【天天抽奖】: 谢谢参与~ x2 【天天抽奖】: 2MB x3 【积分抽奖】: 谢谢参与~ x免费
> > 【游戏中心签到】: 打卡成功，奖励发放失败 【游戏频道打卡】: **积分领取接口:防刷策略接口校验不通过**
> > 我**不清楚**具体原因。
> > 
> > 1. 请求添加一个GitHub Environments 用来设置延时时长，**个性化**调整脚本**执行时间**的功能
> 
> 可以，我一会看下触发接口校验是什么原因，貌似调整执行时间也不能解决。

更新一下最新代码看看

**Comment by hillockgang** [comment]
> > > 【每日签到】: 错误，原因为: **Expecting value: line 1 column 1 (char 0)**
> > > 【天天抽奖】: 谢谢参与~ x1 【天天抽奖】: 谢谢参与~ x2 【天天抽奖】: 2MB x3 【积分抽奖】: 谢谢参与~ x免费
> > > 【游戏中心签到】: 打卡成功，奖励发放失败 【游戏频道打卡】: **积分领取接口:防刷策略接口校验不通过**
> > > 我**不清楚**具体原因。
> > > 
> > > 1. 请求添加一个GitHub Environments 用来设置延时时长，**个性化**调整脚本**执行时间**的功能
> > 
> > 
> > 可以，我一会看下触发接口校验是什么原因，貌似调整执行时间也不能解决。
> 
> 更新一下最新代码看看

今天的自动任务并没有出错（**旧版本**运行，昨天手动同步了一下项目）

```
- 2021-02-22T20:45:34.7023101Z [2***21-***2-22 2***:45:34,7***]:INFO:【登录】: 4591
- 2021-02-22T20:45:39.5283572Z [2***21-***2-22 2***:45:39,527]:INFO:【每日签到】: 打卡成功,翻倍成功
- 2021-02-22T20:45:55.8685510Z [2***21-***2-22 2***:45:55,866]:INFO:【天天抽奖】: 谢谢参与~ x1
- 2021-02-22T20:46:07.2171671Z [2***21-***2-22 2***:46:***7,216]:INFO:【天天抽奖】: 谢谢参与~ x2
- 2021-02-22T20:46:27.5700579Z [2***21-***2-22 2***:46:27,569]:INFO:【天天抽奖】: 2MB x3
- 2021-02-22T20:46:47.3620044Z [2***21-***2-22 2***:46:47,361]:INFO:【积分抽奖】: 谢谢参与~ x免费
- 2021-02-22T20:46:47.7641036Z [2***21-***2-22 2***:46:47,763]:INFO:【游戏中心签到】: 获得4积分
- 2021-02-22T20:47:05.1659102Z [2***21-***2-22 2***:47:***5,163]:INFO:【游戏频道打卡】: 获得1积分
- 2021-02-22T20:47:20.1886866Z [2***21-***2-22 2***:47:2***,188]:INFO:【1***定向积分】: 领取成功
- 2021-02-22T20:47:34.7753212Z [2***21-***2-22 2***:47:34,774]:INFO:【东奥积分活动】: 领取成功，3***积分
- 2021-02-22T20:47:50.4695415Z [2***21-***2-22 2***:47:5***,468]:INFO:【沃之树-领流量】: 4M流量 x1
- 2021-02-22T20:48:08.0176573Z [2***21-***2-22 2***:48:***8,***16]:INFO:【沃之树-领流量】: 4M流量 x2
- 2021-02-22T20:48:20.3653381Z [2***21-***2-22 2***:48:2***,364]:INFO:【沃之树-领流量】: 4M流量 x3
- 2021-02-22T20:48:38.0130483Z [2***21-***2-22 2***:48:38,***12]:INFO:【沃之树-浇水】: 获得3培养值
- 2021-02-22T20:49:07.8167723Z [2***21-***2-22 2***:49:***7,816]:INFO:【1***M寻宝箱】: 获得1***M流量
- 2021-02-22T20:49:23.6854072Z [2***21-***2-22 2***:49:23,684]:INFO:【4G流量包-看视频】: 获得3***M流量 x1
- 2021-02-22T20:49:38.0482234Z [2***21-***2-22 2***:49:38,***47]:INFO:【4G流量包-下软件】: 获得5***M流量 x1
- 2021-02-22T20:49:50.4519607Z [2***21-***2-22 2***:49:5***,451]:INFO:【4G流量包-看视频】: 获得3***M流量 x2
- 2021-02-22T20:50:06.8220373Z [2***21-***2-22 2***:5***:***6,821]:INFO:【4G流量包-下软件】: 获得5***M流量 x2
- 2021-02-22T20:50:21.1956070Z [2***21-***2-22 2***:5***:21,194]:INFO:【4G流量包-看视频】: 获得3***M流量 x3
- 2021-02-22T20:50:33.6542465Z [2***21-***2-22 2***:5***:33,653]:INFO:【4G流量包-下软件】: 获得5***M流量 x3

```
那种情况只遇到过一次
现在已经重新同步项目了，运行结果看明天吧，以下是同步后的运行结果，因为今天**已经成功运行**过一次了，所以没有太大参考意义。

```
- 2021-02-23T06:41:05.6570282Z [2***21-***2-23 14:41:***5,655]:INFO:【登录】: 4591
- 2021-02-23T06:41:11.4372969Z [2***21-***2-23 14:41:11,436]:INFO:【每日签到】: 您今天已经签到啦
- 2021-02-23T06:41:16.6959041Z [2***21-***2-23 14:41:16,695]:INFO:【天天抽奖】: 用户机会次数不足 x1
- 2021-02-23T06:41:18.0287661Z [2***21-***2-23 14:41:18,***28]:INFO:【天天抽奖】: 用户机会次数不足 x2
- 2021-02-23T06:41:19.3432856Z [2***21-***2-23 14:41:19,342]:INFO:【天天抽奖】: 用户机会次数不足 x3
- 2021-02-23T06:41:21.0892551Z [2***21-***2-23 14:41:21,***88]:INFO:【积分抽奖】: 用户机会次数不足 x免费
- 2021-02-23T06:41:22.6326273Z [2***21-***2-23 14:41:22,631]:INFO:【1***定向积分】: 不可重复领取
- 2021-02-23T06:41:25.5936735Z [2***21-***2-23 14:41:25,593]:INFO:【东奥积分活动】: 领取失败，已领取请次日在领取
- 2021-02-23T06:41:28.7904254Z [2***21-***2-23 14:41:28,789]:INFO:【沃之树-领流量】: 已领取过 x1
- 2021-02-23T06:41:30.0864897Z [2***21-***2-23 14:41:3***,***83]:INFO:【沃之树-领流量】: 已领取过 x2
- 2021-02-23T06:41:31.3867328Z [2***21-***2-23 14:41:31,386]:INFO:【沃之树-领流量】: 已领取过 x3
- 2021-02-23T06:41:32.9991128Z [2***21-***2-23 14:41:32,998]:INFO:【沃之树-浇水】: 获得***培养值
- 2021-02-23T06:41:34.2852525Z [2***21-***2-23 14:41:34,284]:INFO:【游戏中心签到】: 打卡重复
- 2021-02-23T06:41:35.5787223Z [2***21-***2-23 14:41:35,578]:INFO:【游戏频道打卡】: 游戏积分领取失败,今日已领取过改积分
- 2021-02-23T06:41:43.7283622Z [2***21-***2-23 14:41:43,727]:INFO:【1***M寻宝箱】: 任务失败
- 2021-02-23T06:41:45.0734834Z [2***21-***2-23 14:41:45,***73]:INFO:【4G流量包-看视频】: 已完成 x1
- 2021-02-23T06:41:46.4975224Z [2***21-***2-23 14:41:46,495]:INFO:【4G流量包-下软件】: 已完成 x1
- 2021-02-23T06:41:47.9176117Z [2***21-***2-23 14:41:47,917]:INFO:【4G流量包-看视频】: 已完成 x2
- 2021-02-23T06:41:49.2989715Z [2***21-***2-23 14:41:49,298]:INFO:【4G流量包-下软件】: 已完成 x2
- 2021-02-23T06:41:51.3729205Z [2***21-***2-23 14:41:51,372]:INFO:【4G流量包-看视频】: 已完成 x3
- 2021-02-23T06:41:52.7268657Z [2***21-***2-23 14:41:52,726]:INFO:【4G流量包-下软件】: 已完成 x3
- 2021-02-23T06:41:55.2916809Z 发送成功!
```

**Comment by srcrs** [comment]
@hillockgang 好的，明天看一下吧

**Comment by hillockgang** [comment]
今天的运行日志：

```
- 2021-02-23T17:06:09.2443485Z [2***21-***2-24 ***1:***6:***9,243]:INFO:【登录】: 4591
- 2021-02-23T17:06:20.9837046Z [2***21-***2-24 ***1:***6:2***,983]:INFO:【每日签到】: 打卡成功,翻倍成功
- 2021-02-23T17:06:25.1996835Z [2***21-***2-24 ***1:***6:25,199]:INFO:【天天抽奖】: 谢谢参与~ x1
- 2021-02-23T17:06:26.5980938Z [2***21-***2-24 ***1:***6:26,595]:INFO:【天天抽奖】: 谢谢参与~ x2
- 2021-02-23T17:06:28.0442339Z [2***21-***2-24 ***1:***6:28,***43]:INFO:【天天抽奖】: 2MB x3
- 2021-02-23T17:06:30.4859253Z [2***21-***2-24 ***1:***6:3***,485]:INFO:【积分抽奖】: 谢谢参与~ x免费
- 2021-02-23T17:06:32.8001285Z [2***21-***2-24 ***1:***6:32,799]:ERROR:【1***定向积分】: 错误，原因为: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char ***)
- 2021-02-23T17:06:33.4460923Z [2***21-***2-24 ***1:***6:33,445]:ERROR:【东奥积分活动】: 错误，原因为: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char ***)
- 2021-02-23T17:06:34.3335194Z [2***21-***2-24 ***1:***6:34,332]:INFO:【沃之树-领流量】: 4M流量 x1
- 2021-02-23T17:06:36.3399163Z [2***21-***2-24 ***1:***6:36,339]:INFO:【沃之树-领流量】: 4M流量 x2
- 2021-02-23T17:06:37.7157410Z [2***21-***2-24 ***1:***6:37,715]:INFO:【沃之树-领流量】: 4M流量 x3
- 2021-02-23T17:06:39.9527975Z [2***21-***2-24 ***1:***6:39,952]:INFO:【沃之树-浇水】: 获得3培养值
- 2021-02-23T17:06:41.3864966Z [2***21-***2-24 ***1:***6:41,386]:INFO:【游戏中心签到】: 获得5积分
- 2021-02-23T17:06:46.3423329Z [2***21-***2-24 ***1:***6:46,341]:INFO:【游戏频道打卡】: 获得1积分
- 2021-02-23T17:06:57.4472873Z [2***21-***2-24 ***1:***6:57,446]:INFO:【1***M寻宝箱】: 获得1***M流量
- 2021-02-23T17:06:58.9592275Z [2***21-***2-24 ***1:***6:58,958]:INFO:【4G流量包-看视频】: 获得3***M流量 x1
- 2021-02-23T17:07:00.4258609Z [2***21-***2-24 ***1:***7:***,425]:INFO:【4G流量包-下软件】: 获得5***M流量 x1
- 2021-02-23T17:07:01.9563875Z [2***21-***2-24 ***1:***7:***1,956]:INFO:【4G流量包-看视频】: 获得3***M流量 x2
- 2021-02-23T17:07:03.4638796Z [2***21-***2-24 ***1:***7:***3,463]:INFO:【4G流量包-下软件】: 获得5***M流量 x2
- 2021-02-23T17:07:04.9306410Z [2***21-***2-24 ***1:***7:***4,93***]:INFO:【4G流量包-看视频】: 获得3***M流量 x3
- 2021-02-23T17:07:06.3925699Z [2***21-***2-24 ***1:***7:***6,389]:INFO:【4G流量包-下软件】: 获得5***M流量 x3
- 2021-02-23T17:07:09.1737703Z Traceback (most recent call last):
- 2021-02-23T17:07:09.1739809Z   File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 234, in day1***Integral_task
- 2021-02-23T17:07:09.1740676Z     res = integral.json()
- 2021-02-23T17:07:09.1742510Z   File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/models.py", line 897, in json
- 2021-02-23T17:07:09.1743589Z     return complexjson.loads(self.text, **kwargs)
- 2021-02-23T17:07:09.1744563Z   File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/__init__.py", line 335, in loads
- 2021-02-23T17:07:09.1745857Z     raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
- 2021-02-23T17:07:09.1747334Z json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char ***)
- 2021-02-23T17:07:09.1748126Z 
- 2021-02-23T17:07:09.1748618Z Traceback (most recent call last):
- 2021-02-23T17:07:09.1749513Z   File "/home/runner/work/UnicomTask/UnicomTask/main.py", line 281, in dongaoPoints_task
- 2021-02-23T17:07:09.1750388Z     res1 = dongaoPoint.json()
- 2021-02-23T17:07:09.1751628Z   File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/models.py", line 897, in json
- 2021-02-23T17:07:09.1752682Z     return complexjson.loads(self.text, **kwargs)
- 2021-02-23T17:07:09.1754020Z   File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/__init__.py", line 335, in loads
- 2021-02-23T17:07:09.1755332Z     raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
- 2021-02-23T17:07:09.1756791Z json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char ***)
- 2021-02-23T17:07:09.1757582Z 
- 2021-02-23T17:07:09.1758111Z 发送成功!
```

**Comment by srcrs** [comment]
@hillockgang 我怀疑会有黑号机制，我每天都会触发这个防刷校验规则

**Comment by srcrs** [comment]
@hillockgang 暂时也不知道什么原因导致的。

**Comment by Just-Nothing** [comment]
我好像也有这个问题

【每日签到】: 打卡成功,翻倍成功 【天天抽奖】: 谢谢参与~ x1 【天天抽奖】: 谢谢参与~ x2 【天天抽奖】: 2MB x3 【积分抽奖】: 谢谢参与~ x免费 【100定向积分】: 领取成功 【东奥积分活动】: 领取成功，300积分 【沃之树-领流量】: 4M流量 x1 【沃之树-领流量】: 4M流量 x2 【沃之树-领流量】: 4M流量 x3 【沃之树-浇水】: 获得3培养值 【游戏中心签到】: 打卡成功，奖励发放失败 【游戏频道打卡】: 积分领取接口:防刷策略接口校验不通过 【100M寻宝箱】: 任务失败 【4G流量包-看视频】: 获得30M流量 x1 【4G流量包-下软件】: 获得50M流量 x1 【4G流量包-看视频】: 获得30M流量 x2 【4G流量包-下软件】: 获得50M流量 x2 【4G流量包-看视频】: 获得30M流量 x3 【4G流量包-下软件】: 获得50M流量 x3

**Comment by srcrs** [comment]
> 我好像也有这个问题
> 
> 【每日签到】: 打卡成功,翻倍成功 【天天抽奖】: 谢谢参与~ x1 【天天抽奖】: 谢谢参与~ x2 【天天抽奖】: 2MB x3 【积分抽奖】: 谢谢参与~ x免费 【100定向积分】: 领取成功 【东奥积分活动】: 领取成功，300积分 【沃之树-领流量】: 4M流量 x1 【沃之树-领流量】: 4M流量 x2 【沃之树-领流量】: 4M流量 x3 【沃之树-浇水】: 获得3培养值 【游戏中心签到】: 打卡成功，奖励发放失败 【游戏频道打卡】: 积分领取接口:防刷策略接口校验不通过 【100M寻宝箱】: 任务失败 【4G流量包-看视频】: 获得30M流量 x1 【4G流量包-下软件】: 获得50M流量 x1 【4G流量包-看视频】: 获得30M流量 x2 【4G流量包-下软件】: 获得50M流量 x2 【4G流量包-看视频】: 获得30M流量 x3 【4G流量包-下软件】: 获得50M流量 x3

貌似和网络有关系，今天在本地运行成功了。

**Comment by bugme2** [comment]
> > 我好像也有这个问题
> > 【每日签到】: 打卡成功,翻倍成功 【天天抽奖】: 谢谢参与~ x1 【天天抽奖】: 谢谢参与~ x2 【天天抽奖】: 2MB x3 【积分抽奖】: 谢谢参与~ x免费 【100定向积分】: 领取成功 【东奥积分活动】: 领取成功，300积分 【沃之树-领流量】: 4M流量 x1 【沃之树-领流量】: 4M流量 x2 【沃之树-领流量】: 4M流量 x3 【沃之树-浇水】: 获得3培养值 【游戏中心签到】: 打卡成功，奖励发放失败 【游戏频道打卡】: 积分领取接口:防刷策略接口校验不通过 【100M寻宝箱】: 任务失败 【4G流量包-看视频】: 获得30M流量 x1 【4G流量包-下软件】: 获得50M流量 x1 【4G流量包-看视频】: 获得30M流量 x2 【4G流量包-下软件】: 获得50M流量 x2 【4G流量包-看视频】: 获得30M流量 x3 【4G流量包-下软件】: 获得50M流量 x3
> 
> 貌似和网络有关系，今天在本地运行成功了。

大佬，建议添加一个每天自动兑换流量的功能，零钱账户里的流量。

**Comment by srcrs** [comment]
> > > 我好像也有这个问题
> > > 【每日签到】: 打卡成功,翻倍成功 【天天抽奖】: 谢谢参与~ x1 【天天抽奖】: 谢谢参与~ x2 【天天抽奖】: 2MB x3 【积分抽奖】: 谢谢参与~ x免费 【100定向积分】: 领取成功 【东奥积分活动】: 领取成功，300积分 【沃之树-领流量】: 4M流量 x1 【沃之树-领流量】: 4M流量 x2 【沃之树-领流量】: 4M流量 x3 【沃之树-浇水】: 获得3培养值 【游戏中心签到】: 打卡成功，奖励发放失败 【游戏频道打卡】: 积分领取接口:防刷策略接口校验不通过 【100M寻宝箱】: 任务失败 【4G流量包-看视频】: 获得30M流量 x1 【4G流量包-下软件】: 获得50M流量 x1 【4G流量包-看视频】: 获得30M流量 x2 【4G流量包-下软件】: 获得50M流量 x2 【4G流量包-看视频】: 获得30M流量 x3 【4G流量包-下软件】: 获得50M流量 x3
> > 
> > 貌似和网络有关系，今天在本地运行成功了。
> 
> 大佬，建议添加一个每天自动兑换流量的功能，零钱账户里的流量。

好的，最近比较忙，有时间会做的。

**Comment by EdisonCC** [comment]
我也是出现同样的问题，已经用了最新版的

**Comment by srcrs** [comment]
> 我也是出现同样的问题，已经用了最新版的

最好换到云函数版，这个好像是网络的问题。

**Comment by vonxing** [comment]
> > 我也是出现同样的问题，已经用了最新版的
> 
> 最好换到云函数版，这个好像是网络的问题。

我这边用actions时也是这个问题.换了云函数就没了

**Comment by bearcony** [comment]
我的也是一样，还是不行，第一次手动执行的就行。

**Comment by EdisonCC** [comment]
切换了云函数 还是同样出现防刷策略接口校验不通过

**Comment by srcrs** [comment]
@bearcony @EdisonCC 好的，我再找找原因吧。

**Comment by bearcony** [comment]
我的用云函数也不行，连7天的奖励也不给了，游戏频道那里看来又升级了吗

**Comment by srcrs** [comment]
@All 貌似解决了，我突然意识到，苹果端是没有游戏中心积分签到的。

**Comment by zongwong** [comment]
新来的 昨天第一天正常 第二天就这样了
***2021-03-08 23:44:46,276***:INFO:【游戏频道打卡】: 积分领取接口:防刷策略接口校验不通过
***2021-03-08 23:44:51,861***:INFO:【100M寻宝箱】: 任务失败

**Comment by zongwong** [comment]
我是新号 第一天正常, 第二天游戏频道的签到和找宝箱就触发防刷了

**Comment by EdisonCC** [comment]
【登录】: 9999【通信积分】: 0 【奖励积分】: 64 【定向积分】: 5900 【每日签到】: 您今天已经签到啦 【1G流量日包】: 已领取 【天天抽奖】: 用户机会次数不足 x1 【天天抽奖】: 用户机会次数不足 x2 【天天抽奖】: 用户机会次数不足 x3 【积分抽奖】: 用户机会次数不足 x免费 【100定向积分】: 不可重复领取 【东奥积分活动】: 领取失败，已领取请次日在领取 【娱乐中心任务】: 触发防刷，跳过 【4G流量包-看视频】: 已完成 x1 【4G流量包-下软件】: 已完成 x1 【4G流量包-看视频】: 已完成 x2 【4G流量包-下软件】: 已完成 x2 【4G流量包-看视频】: 已完成 x3 【4G流量包-下软件】: 已完成 x3 【沃之树-领流量】: 已领取过 x1 【沃之树-领流量】: 已领取过 x2 【沃之树-领流量】: 已领取过 x3 【沃之树-浇水】: 获得0培养值 【即将过期流量包】: 暂无

**Comment by heibaigame** [comment]
大佬，并发数在哪里改呢

**Comment by srcrs** [comment]
@All 最新代码中，已经可以跳过执行此任务。

**Comment by qq1055618906** [comment]
还能更新好吗？？

**Comment by qqhanfeng** [comment]
黑名单机制，不知道怎么解除

**Comment by a6012** [comment]
每天3gb没法领取，大佬什么时候更新一下啊
