### ISSUE TITLE
邮件推送异常

### ISSUE THREAD

**Issue by antfootAlex** [srcrs/UnicomTask#83]
邮件推送异常，原因为: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/runner/work/UnicomTask/UnicomTask/notify.py", line 31, in sendEmail
    res1 = res1.json()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by srcrs** [comment]
@antfootAlex 可能是流星云API出问题了
